# Generated by Django 2.0.7 on 2018-07-19 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(db_index=True, max_length=80)),
                ('blog_url', models.CharField(max_length=150, null=True)),
                ('blog_content', models.TextField()),
                ('blog_date_time', models.DateTimeField(auto_now_add=True)),
                ('blog_view', models.IntegerField(default=0)),
                ('blog_category', models.CharField(db_index=True, max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=48)),
                ('user_url', models.CharField(blank=True, max_length=150, null=True)),
                ('user_sex', models.CharField(blank=True, max_length=16, null=True)),
                ('user_age', models.CharField(blank=True, max_length=40, null=True)),
                ('user_hometown', models.CharField(blank=True, max_length=40, null=True)),
                ('user_birth', models.CharField(blank=True, max_length=40, null=True)),
                ('user_status', models.CharField(blank=True, max_length=16, null=True)),
                ('user_star', models.CharField(blank=True, max_length=16, null=True)),
                ('user_blood', models.CharField(blank=True, max_length=16, null=True)),
                ('user_height', models.IntegerField(blank=True, null=True)),
                ('user_shape', models.CharField(blank=True, max_length=16, null=True)),
                ('user_aim', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user'),
        ),
    ]
