# Generated by Django 2.0.7 on 2018-07-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
